modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/Vg34100/Minecraft-StructureVoidable/issues"
license = "MIT"

[[mods]]
modId = "structurevoidable"
version = "${version}"
displayName = "Structure Voidable"
authors = "VgLevelUp"
description = '''
Client side mod to make using the block Structure Void easier
'''
logoFile = "assets/structurevoidable/icon.png"

[[dependencies.structurevoidable]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.structurevoidable]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.structurevoidable]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
