modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "structurevoidable"
version = "${version}"
displayName = "StructureVoidable"
authors = "VgLevelUp"
description = '''

'''
#logoFile = ""

[[dependencies.structurevoidable]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.structurevoidable]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.structurevoidable]]
modId = "architectury"
type = "required"
versionRange = "[15.0.3,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "structurevoidable.mixins.json"
